# Generated by Django 5.1.1 on 2025-03-12 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('about', models.TextField()),
                ('type', models.CharField(choices=[('Consultancy Services', 'Consultancy Services'), ('General Contracting', 'General Contracting'), ('Electro-Mechanical Works', 'Electro-Mechanical Works'), ('Design & Drafting Services', 'Design & Drafting Services'), ('IT Solutions', 'IT Solutions'), ('Video Production Services', 'Video Production Services')], max_length=100)),
                ('added_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('position', models.CharField(choices=[('Sales Member', 'Sales Member'), ('Team Leads', 'Team Leads'), ('Team Members', 'Team Members'), ('Sub-Contractors', 'Sub-Contractors'), ('Accountant Members', 'Accountant Members')], max_length=50)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('AED', 'AED'), ('USD', 'USD'), ('INR', 'INR'), ('SAR', 'SAR')], default='AED', max_length=3)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='BaseApp.company')),
            ],
        ),
    ]
