# Generated by Django 5.1.1 on 2025-04-08 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timesheet',
            options={'ordering': ['-date_logged']},
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='updated_at',
        ),
    ]
