# Generated by Django 5.1.1 on 2025-03-12 10:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BaseApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=255)),
                ('contact_info', models.CharField(blank=True, max_length=255, null=True)),
                ('company_name', models.CharField(max_length=255)),
                ('service', models.CharField(blank=True, choices=[('Consultancy Services', 'Consultancy Services'), ('General Contracting', 'General Contracting'), ('Electro-Mechanical Works', 'Electro-Mechanical Works'), ('Design & Drafting Services', 'Design & Drafting Services'), ('IT Solutions', 'IT Solutions'), ('Video Production Services', 'Video Production Services')], max_length=100, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aob', models.TextField(blank=True, null=True)),
                ('contact_person', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Expense Categories',
            },
        ),
        migrations.CreateModel(
            name='JobCard',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_number', models.CharField(max_length=20, unique=True)),
                ('scope_of_work', models.TextField()),
                ('delivery_timelines', models.DateField()),
                ('payment_terms', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed')], default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('color_status', models.CharField(choices=[('gray', 'Gray'), ('blue', 'Blue'), ('purple', 'Purple'), ('pink', 'Pink'), ('green', 'Green')], default='gray', max_length=6)),
                ('client_name', models.CharField(editable=False, max_length=255)),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('project_expense', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_timesheet_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gross_profit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('profit_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('lpo_number', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentBall',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('project_status', models.CharField(choices=[('Pending', 'Pending'), ('InProgress', 'InProgress'), ('Completed', 'Completed')], default='Pending', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('color_status', models.CharField(choices=[('gray', 'Gray'), ('blue', 'Blue'), ('purple', 'Purple'), ('pink', 'Pink'), ('green', 'Green')], default='gray', max_length=6)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_terms', models.TextField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('verified', 'Verified'), ('invoiced', 'Invoiced'), ('paid', 'Paid')], default='unverified', max_length=20)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('payment_received_date', models.DateTimeField(blank=True, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=20, null=True)),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_balls', to='client_new.jobcard')),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to='BaseApp.employee')),
            ],
        ),
        migrations.CreateModel(
            name='RFQ',
            fields=[
                ('rfq_id', models.AutoField(primary_key=True, serialize=False)),
                ('rfq_date', models.DateTimeField(auto_now_add=True)),
                ('project_type', models.CharField(max_length=255)),
                ('scope_of_work', models.TextField()),
                ('quotation_number', models.CharField(max_length=20, unique=True)),
                ('quotation_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed')], default='Pending', max_length=50)),
                ('is_approved', models.BooleanField(default=False)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_rfqs', to='BaseApp.employee')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfqs', to='client_new.client')),
            ],
        ),
        migrations.AddField(
            model_name='jobcard',
            name='rfq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_cards', to='client_new.rfq'),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('expense_id', models.AutoField(primary_key=True, serialize=False)),
                ('lpo_number', models.CharField(blank=True, editable=False, max_length=20, null=True)),
                ('expense_type', models.CharField(choices=[('Material', 'Material'), ('Labor', 'Labor'), ('Equipment', 'Equipment'), ('Transportation', 'Transportation'), ('Subcontractor', 'Subcontractor'), ('Other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('net_amount', models.DecimalField(decimal_places=2, help_text='Net amount without tax', max_digits=10)),
                ('vat_percentage', models.DecimalField(decimal_places=2, default=5.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('vat_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, editable=False, help_text='Total amount including VAT', max_digits=10)),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Bank Transfer', 'Bank Transfer'), ('Credit Card', 'Credit Card'), ('Other', 'Other')], default='Cash', max_length=20)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client_new.expensecategory')),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='client_new.jobcard')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='client_new.supplier')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_brief', models.TextField()),
                ('weightage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('InProgress', 'InProgress'), ('Completed', 'Completed')], default='Pending', max_length=50)),
                ('due_date', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('remarks_history', models.JSONField(blank=True, default=list)),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='BaseApp.employee')),
                ('payment_ball', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='client_new.paymentball')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubContracting',
            fields=[
                ('subcontract_id', models.AutoField(primary_key=True, serialize=False)),
                ('subcontract_brief', models.TextField()),
                ('weightage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('InProgress', 'InProgress'), ('Completed', 'Completed')], default='Pending', max_length=50)),
                ('due_date', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_subcontracts', to='BaseApp.employee')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcontracts', to='client_new.task')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
