# Generated by Django 5.1.1 on 2025-04-08 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_new', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='jobcard', to='client_new.client'),
            preserve_default=False,
        ),
    ]
