# Generated by Django 5.1.1 on 2025-01-28 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_new', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'verbose_name_plural': 'Expense Categories'},
        ),
    ]
