# Generated by Django 5.1.1 on 2025-03-06 10:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_new', '0002_rfq_approval_date_rfq_approved_by_rfq_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Task_completion_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
