# Generated by Django 5.1.1 on 2025-02-21 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp', '0001_initial'),
        ('client_new', '0002_alter_expensecategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentball',
            name='payment_received_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentball',
            name='verification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentball',
            name='verification_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('verified', 'Verified'), ('invoiced', 'Invoiced'), ('paid', 'Paid')], default='unverified', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentball',
            name='verified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to='BaseApp.employee'),
        ),
    ]
