# Generated by Django 5.1.1 on 2025-03-06 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_new', '0003_task_task_completion_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='Task_completion_percentage',
        ),
        migrations.AddField(
            model_name='task',
            name='remarks_history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
